<a href="https://colab.research.google.com/github/WojtMacz/analiza-danych-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawy

In [3]:
import numpy as np
np.__version__

'1.18.5'

1D Array - One Dimensional Array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x = np.array([1.3, 2.3, 1.4])
x

array([1.3, 2.3, 1.4])

In [ ]:
x.dtype

dtype('float64')

2D Array

In [ ]:
np.array([[1, 2], [-3, 1]])


array([[ 1,  2],
       [-3,  1]])

In [ ]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2,  3],
       [-3,  1,  0]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 3)

In [ ]:
x = np.array([[1, 2, 3], [4, 2, 1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array(
    [[[4, 3, 1], 
      [3, 1, 5]],
      
      [[5, 2, 1], 
       [4, 2, 1]],
     [[5, 3, 1],
      [9, 7, 5]]])
x

array([[[4, 3, 1],
        [3, 1, 5]],

       [[5, 2, 1],
        [4, 2, 1]],

       [[5, 3, 1],
        [9, 7, 5]]])

In [ ]:
x.ndim # wymiar tablicy

3

In [ ]:
x.shape # (3 tablice, 2 wiersze, 3 kolumny)

(3, 2, 3)

Typy danych

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1, 4, 2], dtype = 'float')
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 4, 2], dtype = 'complex')
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.0, 4.3, 2.6], dtype = 'int')
A.dtype

dtype('int64')

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8) #uint - unsite integer
A.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape=(4, 10)) # tworzy tablice o rozmierze 4 wierszy i 10 kolumn wypełnionymi zerami


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4, 10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11) # funkcja wyścietla nam równo rozłożonych elementów 'num' w zakresie od start do stop

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
#zmiana rozmiaru tablicy
A.reshape((3, 5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((5, -1)) # określam ile chcę wierszy a program określa ile ma być kolumn w danym zakresie tablicy A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach

In [4]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [5]:
A + B

array([6, 0, 7, 4])

In [6]:
A - B

array([0, 2, 1, 0])

In [7]:
A * B

array([ 9, -1, 12,  4])

In [8]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [12]:
np.add(A, B)


array([6, 0, 7, 4])

In [13]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [14]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [15]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [10]:
A + 3

array([6, 4, 7, 5])

In [11]:
A + 3*B

array([12, -2, 13,  8])

In [19]:
x = np.array([[1, 3], [-2, 0]])
y = np.array([[6,0], [-1, 2]])
print(x, '\n')
print(y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [20]:
x * y

array([[6, 0],
       [2, 0]])

In [21]:
np.dot(x, y) # monożenie macierzy przez siebie licznik razy kolumna drugiej macierzy:
            # (1*6+3*(-1)) =3; 3*0+ 3*2 =6 pierwszy wiersz to szą liczby 3 i 6
            # -2*6 + 0*(-1) = -12; -2*0 + 0*2 = 0 w drugim wierszu będą -12 i 0

array([[  3,   6],
       [-12,   0]])

In [22]:
x.dot(y)

array([[  3,   6],
       [-12,   0]])

In [23]:
y.dot(x)

array([[ 6, 18],
       [-5, -3]])

In [24]:
x @ y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [25]:
np.random.randn()

-2.270204057903513

In [26]:
np.random.randn(10)

array([ 0.32286543,  0.8047654 ,  0.22594582,  0.98012426,  0.16053379,
       -0.57582341,  0.97567056,  0.59462257, -0.55430579,  0.92649098])

In [27]:
np.random.randn(10, 4) #liczba wierszy (liczba próbek), liczba kolumn (ilość zmiennych) 
                      #randn wyświetla nam losow liczby z rozkładu normalnego

array([[ 0.75776737, -0.18722621,  0.16878075, -0.19856166],
       [ 0.2693831 ,  1.37427132,  0.65351419, -0.85013763],
       [-1.52242048,  0.64430946, -1.92712507, -0.14395673],
       [ 1.23995001,  1.91348755,  0.30384914,  2.30129313],
       [-0.80824251, -1.37729766, -0.58259625,  0.56336615],
       [-0.70568518, -0.26961119, -1.30604334, -1.38020231],
       [ 0.44559861,  1.53127739,  0.44266219,  0.97821795],
       [ 1.70392536,  0.1419627 ,  0.8524205 , -0.71622488],
       [-0.74123621, -0.6813446 ,  1.32420545, -1.79698035],
       [-0.59986379,  1.506586  , -1.18705904,  0.05240474]])

In [28]:
np.random.rand()

0.08657567339520689

In [29]:
np.random.rand(10)

array([0.26207597, 0.02768669, 0.80046595, 0.37914088, 0.41441253,
       0.56087849, 0.89036253, 0.96841855, 0.16614555, 0.74307324])

In [30]:
np.random.rand(10, 2)

array([[0.51891631, 0.40740276],
       [0.46250022, 0.29705443],
       [0.81861841, 0.3954697 ],
       [0.48868601, 0.55179782],
       [0.07172318, 0.75534408],
       [0.83154833, 0.96771267],
       [0.95657485, 0.92642354],
       [0.91888717, 0.26063964],
       [0.50763292, 0.67239799],
       [0.64944331, 0.05456248]])

In [31]:
np.random.randint(10) #zwraca nam liczbę całkowitą mniejszą od 10 i większą od 0

7

In [32]:
np.random.randint(low=10, high=101)

44

In [34]:
np.random.randint(low=10, high=101, size=10)

array([84, 59, 79, 75, 62, 31, 81, 40, 90, 30])

In [35]:
np.random.choice([4, 2, 1, 3]) #zwraca losowy element z listy

2

In [36]:
np.random.choice(['python', 'java', 'sql', 'c++'])

'python'

In [39]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.shuffle(data) #zmienia pozycje w tablicy data

In [43]:
data

array([7, 4, 8, 9, 1, 3, 2, 5, 0, 6])

Podstawowe funkcje w bibliotece NumPy

In [44]:
np.exp(1)

2.718281828459045

In [ ]:
np.sqrt(9)

In [45]:
np.all([2, 3, 1])

True

In [46]:
np.any([1, 2, 1]) # sprawdza czy jakikolwiek obiekt jest prawdą

True

In [47]:
np.any([0, 0, 0])

False

In [49]:
bool(1.3)

True

In [51]:
a = np.random.rand(5)
a

array([0.11396034, 0.34141299, 0.5960272 , 0.89410617, 0.00210857])

In [54]:
np.argmax(A)


2

In [53]:
a[np.argmax(a)]

0.8941061709153063

In [55]:
np.argmin(a)

4

In [56]:
np.argsort(a)

array([4, 0, 1, 2, 3])

In [57]:
np.max(a)

0.8941061709153063

In [58]:
np.min(a)

0.0021085654082670935

In [59]:
np.mean(a)

0.38952305295989315

In [60]:
np.median(a)

0.3414129910658096

In [61]:
np.std(a)

0.3242182774534286

Indeksowanie, Wycinanie

In [63]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
# a[idx], a[start:stop], a[:stop], a[start:]
a[2]

2

In [65]:
a[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [66]:
a[:2]

array([0, 1])

In [67]:
a[[0, 2]]

array([0, 2])

In [68]:
a[-1]

19

In [69]:
a[10:15]

array([10, 11, 12, 13, 14])

In [70]:
a = a.reshape(4, 5) # zmiana wygenerowanej tablicy jednowymiarowej na 4 wiersze i 5 kolumn
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [71]:
a[0] # wycięcie konkretengo wiersza

array([0, 1, 2, 3, 4])

In [72]:
a[1]

array([5, 6, 7, 8, 9])

In [73]:
a[:, 0] # wycięcie konkretnej kolumny

array([ 0,  5, 10, 15])

In [76]:
a[:, -2]

array([ 3,  8, 13, 18])

In [78]:
# wycięcie konkretnego indeksu
a[1, 3]

8

In [79]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [82]:
a[1, 2] = 14 #zamiana 7 na 14 wiersz 1 kolumna 2 (liczenie zaczyna się od 0)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
a[2:, 2:]


array([[12, 13, 14],
       [17, 18, 19]])

Iteracja po tablicach

In [89]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
for row in a:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [91]:
for row in a:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [92]:
for item in a.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [93]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
a.shape

(4, 5)

In [95]:
a.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [97]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [98]:
a.T #transport macierzy

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski

In [101]:
a = np.arange(start=-10, stop=10, step=0.5)
a = a.reshape(10, -1)
a

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [102]:
a > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [103]:
a[a > 0 ]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [104]:
a[np.bitwise_and(a > -5, a < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [105]:
np.bitwise_or(a < -0.5, a > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

Broadcasting