<a href="https://colab.research.google.com/github/WojtMacz/analiza-danych-bootcamp/blob/main/01_wprowadzenie/02_Algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Norma wektora i odległość punktów

In [6]:
import numpy as np
np.__version__

'1.18.5'

In [9]:
v1 = np.array([-1, 4]) #przestrzeń euklidesowa dwa wymiary
v1

array([-1,  4])

In [10]:
np.linalg.norm(v1)

4.123105625617661

In [11]:
v2 = np.array([-10, 10, 13]) # przestrzeń R(n)
np.linalg.norm(v2)

19.209372712298546

In [12]:
#odległość dwóch punkto na płaszczyźnie
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p-q)

5.0

In [13]:
#odległość dwóch punkto w przestrzeni R o n-wymiarach
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy


A - macierz wymiaru m x n (wiersze x kolumny)
B - maczierz wymaru n x p
Aby móc ponożyć dwie macierze liczba kolumn w lewej macierzy musi się zgadzać z liczbą wierszy prawej macierzy
Mnożenie macierzy nie jest przemienne.

In [15]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, '\n')
print(Y)


[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [16]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [17]:
Z.shape

(2, 1)

In [18]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2, 0]])
print(X, '\n')
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [19]:
Z = np.dot(X, Y)
Z

array([[13,  9, -4],
       [ 6,  2, -1]])

Wyznacznik, macierz jednostkowa, odwrotna i transponowana

In [21]:
# wyznacznik
a = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(a))

10.0

In [22]:
# ślad macierzy
a = np.array([[2, 4], [-1, 3]])
np.trace(a)


5

In [23]:
# Macierz jednostkowa
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [26]:
# Macierz odwrotna dotyczy macierzy kwadratowych
a = np.array([[2, 4], [-1, 3]])
b = np.linalg.inv(a)
b

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [27]:
#sprawdzenie czy macież jest odwrotna mnożymy uzskaną macież przez macierz orguinalną
# i musi powstać macierz jednostkowa
np.set_printoptions(precision=4, suppress=True)
np.dot(a, b)

array([[1., 0.],
       [0., 1.]])

In [28]:
# macierz transporotowana
a

array([[ 2,  4],
       [-1,  3]])

In [29]:
a.T

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [30]:
A = np.array([[2, 4],[1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [31]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [32]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])

Funkcje statystyczne