<a href="https://colab.research.google.com/github/WojtMacz/analiza-danych-bootcamp/blob/main/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [5]:
# tworzymy listę np. cen giełdowych dla spółki z trzech kolejnych dni
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 17.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    17.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [6]:
# sumowanie
price.sum()

4656.1

In [7]:
price.sum(axis=0) #sumowanie po kolumnach wpisujemy 0

array([  37.1,   39.2,   41.8,   38. , 4500. ])

In [8]:
price.sum(axis=1) #sumowanie po wierszach wpisujemy 1

array([1049.7, 2055.4, 1551. ])

In [9]:
np.sum(price, axis = 0)

array([  37.1,   39.2,   41.8,   38. , 4500. ])

In [10]:
#wartość min
np.min(price)

11.9

In [11]:
np.median(price)

12.8

In [13]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   13.93333333,   12.66666667,
       1500.        ])

In [14]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.66624997e+00, 4.10960934e-01,
       4.08248290e+02])