<a href="https://colab.research.google.com/github/WojtMacz/analiza-danych-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Podstawy

In [2]:
import numpy as np
np.__version__

'1.18.5'

1D Array - One Dimensional Array

In [3]:
x = np.array([1, 3])
x

array([1, 3])

In [4]:
x.dtype

dtype('int64')

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [14]:
x = np.array([1.3, 2.3, 1.4])
x

array([1.3, 2.3, 1.4])

In [15]:
x.dtype

dtype('float64')

2D Array

In [16]:
np.array([[1, 2], [-3, 1]])


array([[ 1,  2],
       [-3,  1]])

In [20]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2,  3],
       [-3,  1,  0]])

In [21]:
x.ndim

2

In [22]:
x.shape

(2, 3)

In [25]:
x = np.array([[1, 2, 3], [4, 2, 1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [24]:
x.shape

(2, 3)

3D Array

In [31]:
x = np.array(
    [[[4, 3, 1], 
      [3, 1, 5]],
      
      [[5, 2, 1], 
       [4, 2, 1]],
     [[5, 3, 1],
      [9, 7, 5]]])
x

array([[[4, 3, 1],
        [3, 1, 5]],

       [[5, 2, 1],
        [4, 2, 1]],

       [[5, 3, 1],
        [9, 7, 5]]])

In [32]:
x.ndim # wymiar tablicy

3

In [33]:
x.shape # (3 tablice, 2 wiersze, 3 kolumny)

(3, 2, 3)

Typy danych

In [34]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [37]:
A = np.array([1, 4, 2], dtype = 'float')
A.dtype

dtype('float64')

In [38]:
A = np.array([1, 4, 2], dtype = 'complex')
A.dtype

dtype('complex128')

In [41]:
A = np.array([1.0, 4.3, 2.6], dtype = 'int')
A.dtype

dtype('int64')

In [42]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [43]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [44]:
A = np.array([24, 120, 230], dtype=np.uint8) #uint - unsite integer
A.dtype

dtype('uint8')

Tworzenie tablic

In [45]:
np.zeros(shape=(4, 10)) # tworzy tablice o rozmierze 4 wierszy i 10 kolumn wypełnionymi zerami


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [46]:
np.zeros(shape=(4, 10), dtype = 'int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [54]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [57]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [59]:
np.linspace(start=0, stop=1, num=11) # funkcja wyścietla nam równo rozłożonych elementów 'num' w zakresie od start do stop

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [61]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [62]:
#zmiana rozmiaru tablicy
A.reshape((3, 5))


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
A.reshape((5, -1)) # określam ile chcę wierszy a program określa ile ma być kolumn w danym zakresie tablicy A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [67]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Podstawowe operacje na tablicach